# Generated by Django 4.2.14 on 2024-08-28 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_alter_post_slug'),
        ('accounts', '0006_userprofile_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='posts_saved',
            field=models.ManyToManyField(blank=True, to='posts.post'),
        ),
    ]
