# Generated by Django 4.2.14 on 2024-08-13 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_postssaved'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostsSaved',
        ),
    ]
